apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-one-svc
            port: { number: 80 }
  - host: app2.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app-two-svc
              port: { number: 80 }

# No host rule defined, default backend
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-three-svc
            port: { number: 80 }
